server:
  port: 9094

spring:
  application:
    name: 03-gateway-service

#addind route configuration
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: 00-user_service
            uri: http://localhost:9091
            predicates:
              - Path=/user/**
            filters:
              - AddRequestHeader=X-Route, UserService